server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: effective-mobile

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migration/liquid-migration.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: SecretKey12345
    expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
